# Pipeline Variables Configuration
# Environment-specific variables for Azure Pipelines
# This file serves as documentation - actual variables should be configured in Azure DevOps Variable Groups

# Development Environment Variables
dev:
  RESOURCE_GROUP: 'portfolio-rg-dev'
  CONTAINER_APP_ENV: 'portfolio-env-dev'
  BACKEND_APP_NAME: 'portfolio-backend-dev'
  FRONTEND_APP_NAME: 'portfolio-frontend-dev'
  ACR_NAME: 'portfolioacrdev'
  MONGODB_URI: 'mongodb://localhost:27017/portfolio_dev'  # Use Key Vault reference in actual pipeline
  CORS_ALLOWED_ORIGINS: 'http://localhost:5173,http://localhost:3000'
  SPRING_PROFILES_ACTIVE: 'dev'

# Staging Environment Variables
staging:
  RESOURCE_GROUP: 'portfolio-rg-staging'
  CONTAINER_APP_ENV: 'portfolio-env-staging'
  BACKEND_APP_NAME: 'portfolio-backend-staging'
  FRONTEND_APP_NAME: 'portfolio-frontend-staging'
  ACR_NAME: 'portfolioacrstaging'
  MONGODB_URI: 'mongodb://staging-mongodb:27017/portfolio_staging'  # Use Key Vault reference
  CORS_ALLOWED_ORIGINS: 'https://portfolio-frontend-staging.azurecontainerapps.io'
  SPRING_PROFILES_ACTIVE: 'staging'

# Production Environment Variables
production:
  RESOURCE_GROUP: 'portfolio-rg-prod'
  CONTAINER_APP_ENV: 'portfolio-env-prod'
  BACKEND_APP_NAME: 'portfolio-backend-prod'
  FRONTEND_APP_NAME: 'portfolio-frontend-prod'
  ACR_NAME: 'portfolioacrprod'
  MONGODB_URI: 'mongodb://prod-cosmosdb:27017/portfolio_prod'  # Use Key Vault reference
  CORS_ALLOWED_ORIGINS: 'https://portfolio-frontend-prod.azurecontainerapps.io'
  SPRING_PROFILES_ACTIVE: 'prod'

# Common Variables (apply to all environments)
common:
  JAVA_VERSION: '21'
  NODE_VERSION: '18.x'
  DOCKER_BUILDKIT: '1'
  BUILD_TIMEOUT: '1800'  # 30 minutes
  TEST_TIMEOUT: '600'    # 10 minutes

# Key Vault References (configure in Azure DevOps)
# These should be linked to Azure Key Vault secrets:
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - JWT_SECRET
# - MONGODB_URI (production)
# - MONGO_ROOT_PASSWORD

# Service Connection Names (configure in Azure DevOps)
service_connections:
  ACR_CONNECTION: 'ACR_Connection'
  AZURE_SUBSCRIPTION: 'Azure_Subscription_Connection'
  KEY_VAULT: 'Key_Vault_Connection'

# Notification Settings
notifications:
  SLACK_WEBHOOK_URL: ''  # Configure in Azure DevOps Variable Group
  TEAMS_WEBHOOK_URL: ''  # Configure in Azure DevOps Variable Group
  EMAIL_RECIPIENTS: ''   # Configure in Azure DevOps Variable Group

